# Generated by Django 4.1.7 on 2023-02-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
